# Generated by Django 5.1.1 on 2024-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0005_usercommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='header',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
